modules:
    - aprs
    - command_ingest
    - gps
#    - imu
aprs:
    #serial_port: /dev/ttyUSB0
    serial_port: /dev/ttyS1
    loglocation: /root/TJREVERB/pFS/submodules/logs/aprs/
gps:
    serial_port: /dev/ttyS3
#telemetry:
#    data_functions:
#        - aprs.get_voltage
#        - aprs.get_number-of_packeut
