core:
    modules:
        - aprs
        - command_ingest
        - gps
    log_dir: logs
aprs:
    #s1
    serial_port: /dev/ttyUSB0
gps:
    #s3
    serial_port: /dev/ttyUSB1
#telemetry:
#    data_functions:
#        - aprs.get_voltage
#        - aprs.get_number-of_packeut
