modules:
    - aprs
    - command_ingest
    - gps
aprs:
    #serial_port: /dev/ttyUSB0
    serial_port: /dev/ttyS0

#telemetry:
#    data_functions:
#        - aprs.get_voltage
#        - aprs.get_number-of_packeut
